version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  mqtt:
    image: eclipse-mosquitto:latest
    network_mode: host
    volumes:
      - ./mqtt-conf:/mosquitto/conf
      - ./data:/mosquitto/data
      - ./logs:/mosquitto/log
