
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  sensor:
    - name: "Temperatur Badezimmer"
      unique_id: 1c06f24427f60d3b8a0c3375b23210c9
      state_topic: "homeassistant/sensor/shellyplusht-c049ef8e0cb4/state/status/temperature:0"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.tC }}"
      device:
        identifiers:
          - "hp_1231232"
        suggested_area: "Bad"
    - name: "Luftfeuchtigkeit Badezimmer"
      unique_id: 7b1cd0e9cda15b0f04fa01afbcbe3cfb
      state_topic: "homeassistant/sensor/shellyplusht-c049ef8e0cb4/state/status/humidity:0"
      unit_of_measurement: "%"
      value_template: "{{ value_json.rh }}"
      device:
        name: "Shelly H&T Bad"
        manufacturer: "Shelly"
        identifiers:
          - "hp_1231232"
        suggested_area: "Bad"
